---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }


    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        gzip  on;
        gzip_types text/plain text/html text/css image/jpeg image/jpg image/png;
        gzip_proxied no-cache no-store private expired auth;

        include /etc/nginx/conf.d/*.conf;
    }


---
apiVersion: v1
kind: Pod
metadata:
  name: web-portfolio
  labels:
    app: web-portfolio
spec:
  imagePullSecrets:
    - name: docker-registry
  containers:
  - name: web-portfolio
    image: jfdona23/web-portfolio
    resources:
      limits:
        memory: "64Mi"
        cpu: "250m"
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: /etc/nginx/nginx.conf
        subPath: nginx.conf      
        name: nginx-config
  volumes:
    - name: nginx-config
      configMap:
        name: nginx-config

---
apiVersion: v1
kind: Service
metadata:
  name: web-portfolio
spec:
  selector:
    app: web-portfolio
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
