name: Terraform Plan

on: [push]

jobs:
  Create_Plans:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_TF_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_TF_SECRET_KEY }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Get Terraform binary
        uses: hashicorp/setup-terraform@v1.2.1 

      - name: Calculating backend plan
        id: plan_backend
        run: cd terraform/backend && terraform init && terraform plan

      - name: Backend plan - stdout
        run: echo ${{ steps.plan_backend.outputs.stdout }}
      - name: Backend plan - stderr
        run: echo ${{ steps.plan_backend.outputs.stderr }}
      - name: Backend plan - exit code
        run: echo ${{ steps.plan_backend.outputs.exitcode }}