name: Terraform Plan

on: [push]

jobs:
  calculate-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Get Terraform CLI
        uses: hashicorp/setup-terraform@v1.2.1 

      - name: Calculating backend plan
        id: plan
        run: cd terraform/backend && terraform plan

      - name: Plan STDOUT
        run: echo ${{ steps.plan.outputs.stdout }}
      - name: Plan STERR
        run: echo ${{ steps.plan.outputs.stderr }}
      - name: Plan exit code
        run: echo ${{ steps.plan.outputs.exitcode }}