name: Terraform Plan

on:
  push:
    paths:
      - "terraform/**"

jobs:
  Create_Plans:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_TF_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_TF_SECRET_KEY }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Get Terraform binary
        uses: hashicorp/setup-terraform@v1.2.1 

      - name: Validate Base config
        run: cd terraform/base && terraform init && terraform validate

      - name: Calculating Base plan
        run: cd terraform/base && terraform plan

      - name: Validate Main config
        run: cd terraform && terraform init && terraform validate

      - name: Calculating Main plan
        run: cd terraform && terraform plan
